version: 3.0.{Build}
build_cloud: houstonlab
image: labwmf5
clone_folder: C:\projects\HPOneView.300
init:
- ps: $env:PSModulePath += ";C:\Projects"
build: off
test_script:
- ps: "& \"C:\\tests\\appveyor.tests.ps1\"\n\nUpdate-AppveyorBuild -VersionÂ $Global:Version"
notifications:
- provider: Email
  to:
  - chris.lynch@hpe.com
  subject: POSH-HPOneView.300 AppVeyor Results
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false