blank_issues_enabled: false
contact_links:
    - name: HPE OneView PowerShell Discussions
      url: https://github.com/HewlettPackard/POSH-HPEOneView/discussions
      about: Ask questions, requests, other topics that are not reporting bugs.
    - name: HPE OneView Community
      url: https://community.hpe.com/t5/HPE-OneView/bd-p/oneview#.X8_eHnCSmUk
      about: HPE community forum to discuss general HPE OneView questions not specific to the HPE OneView PowerShell Library.